#!/usr/bin/env python
from lSdaCollection import LucidSdaCollection
from lSdaField import lsFields
from sys import argv

collName = argv[1]

coll = LucidSdaCollection(collName, autoCreate=False)
coll.stat()

lsFields(coll.fields)
